### ISSUE TITLE
Sequence Diagrams

### ISSUE THREAD

**Issue by lohanspies** [EarthProgram/did-earth#2]
@wip-abramson @jandrieu please find the create, read and deactivate sequence diagrams for did:earth here - https://github.com/EarthProgram/did-earth/tree/draft/diagrams. You can copy and paste them into [this tool](https://sequencediagram.org/) to render the diagrams.

Believe that from my discussions with @jandrieu the create sequence is nearly where we want it to be. 

Deactivate should be fairly simple as my view is that we only need to update the metadata attribute `active` to False to deactivate a DID in the DID registry.

Read is a bit more complex, took a stab at a first draft but sure it needs a discussion between us so that we can agree on the read sequence. Once the read sequence is completed, we can work on the update sequence as it will be very similar and fairly quick and easy to complete.

**Comment by jandrieu** [comment]
Converted into mermaid. Closing.
